/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.SucKhoeManagerFrame;

import Bean.NhanKhauBean;
import Bean.SucKhoeBean;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.StringJoiner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import models.SucKhoeModel;
import services.SucKhoeService;
import views.HoKhauManagerFrame.ChoosePeople;
import views.SucKhoeManagePanel;

/**
 *
 * @author Hoang
 */
public class ThemMoiSucKhoeFrame extends javax.swing.JFrame {
    private NhanKhauBean nhanKhauBean;
    private SucKhoeModel sucKhoeModel;
    private JFrame parentFrame;
    private JPanel parentPanel;
    /**
     * Creates new form TheMoiSucKhoe
     */
    public ThemMoiSucKhoeFrame(JFrame parentFrame, JPanel parentPanel) {
        initComponents();
        this.parentFrame = parentFrame;
        this.parentPanel = parentPanel;
        nhanKhauBean = new NhanKhauBean();
        sucKhoeModel = new SucKhoeModel();
        this.parentFrame.setEnabled(false);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        setTitle("Thêm mới sức khỏe");
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }
        });
        
    }
    public void setDataNhanKhau(){
        this.maNhanKhaujtf.setText(""+this.nhanKhauBean.getNhanKhauModel().getID());
        this.tenNhanKhaujtf.setText(this.nhanKhauBean.getNhanKhauModel().getHoTen());
        this.soCCCDjtf.setText(""+this.nhanKhauBean.getChungMinhThuModel().getSoCMT());
    }
    private void close() {
        this.parentFrame.setEnabled(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        maNhanKhauLabel = new javax.swing.JLabel();
        chooseButton = new javax.swing.JButton();
        maNhanKhaujtf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tenNhanKhauLabel = new javax.swing.JLabel();
        tenNhanKhaujtf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        soCCCDLabel = new javax.swing.JLabel();
        soCCCDjtf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        trieuChungLabel = new javax.swing.JLabel();
        trieuChungCheckBox = new java.awt.Checkbox();
        sucKhoeLabel = new javax.swing.JLabel();
        jCheckBoxBinhThuong = new javax.swing.JCheckBox();
        jCheckBoxHo = new javax.swing.JCheckBox();
        jCheckBoxSot = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jtfKhac = new javax.swing.JTextField();
        Savebtn = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        ngayCapNhatLabel = new javax.swing.JLabel();
        ngayCapNhatJDC = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        maNhanKhauLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        maNhanKhauLabel.setText("Mã nhân khẩu");
        maNhanKhauLabel.setName(""); // NOI18N

        chooseButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        chooseButton.setText("Chọn");
        chooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseButtonActionPerformed(evt);
            }
        });

        maNhanKhaujtf.setEditable(false);
        maNhanKhaujtf.setBackground(new java.awt.Color(240, 240, 240));
        maNhanKhaujtf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        maNhanKhaujtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maNhanKhaujtfActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("(*)");

        tenNhanKhauLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tenNhanKhauLabel.setText("Tên nhân khẩu");
        tenNhanKhauLabel.setName(""); // NOI18N

        tenNhanKhaujtf.setEditable(false);
        tenNhanKhaujtf.setBackground(new java.awt.Color(240, 240, 240));
        tenNhanKhaujtf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tenNhanKhaujtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenNhanKhaujtfActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("(*)");

        soCCCDLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        soCCCDLabel.setText("Số CCCD/CMT");
        soCCCDLabel.setName(""); // NOI18N

        soCCCDjtf.setEditable(false);
        soCCCDjtf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        soCCCDjtf.setText(" ");
        soCCCDjtf.setSelectionEnd(0);
        soCCCDjtf.setSelectionStart(0);
        soCCCDjtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soCCCDjtfActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("(*)");

        trieuChungLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        trieuChungLabel.setText("Triệu chứng Covid");
        trieuChungLabel.setName(""); // NOI18N

        trieuChungCheckBox.setBackground(new java.awt.Color(240, 240, 240));
        trieuChungCheckBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        trieuChungCheckBox.setLabel("Có triệu chứng");

        sucKhoeLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sucKhoeLabel.setText("Tình trạng sức khỏe");
        sucKhoeLabel.setName(""); // NOI18N

        jCheckBoxBinhThuong.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jCheckBoxBinhThuong.setText("Bình thường");
        jCheckBoxBinhThuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBinhThuongActionPerformed(evt);
            }
        });

        jCheckBoxHo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jCheckBoxHo.setText("Ho");
        jCheckBoxHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHoActionPerformed(evt);
            }
        });

        jCheckBoxSot.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jCheckBoxSot.setText("Sốt");
        jCheckBoxSot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSotActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Khác");

        jtfKhac.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtfKhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfKhacActionPerformed(evt);
            }
        });

        Savebtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Savebtn.setText("Lưu");
        Savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebtnActionPerformed(evt);
            }
        });

        backBTN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        backBTN.setText("Trở lại");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        ngayCapNhatLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ngayCapNhatLabel.setText("Ngày cập nhật");
        ngayCapNhatLabel.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(maNhanKhauLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chooseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(maNhanKhaujtf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(tenNhanKhauLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tenNhanKhaujtf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(trieuChungLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(trieuChungCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(sucKhoeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jCheckBoxBinhThuong)
                                    .addGap(49, 49, 49)
                                    .addComponent(jCheckBoxHo))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfKhac)
                                    .addGap(25, 25, 25))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jCheckBoxSot)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(soCCCDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(soCCCDjtf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(10, 10, 10)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ngayCapNhatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ngayCapNhatJDC, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maNhanKhauLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maNhanKhaujtf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenNhanKhauLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenNhanKhaujtf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soCCCDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soCCCDjtf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(trieuChungCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(trieuChungLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jCheckBoxBinhThuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxHo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(sucKhoeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxSot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ngayCapNhatJDC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngayCapNhatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Savebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        Savebtn.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseButtonActionPerformed
        // TODO add your handling code here:
        ChoosePeopleSucKhoe choosePeople = new ChoosePeopleSucKhoe(this.nhanKhauBean, this);
        choosePeople.setLocationRelativeTo(null);
        choosePeople.setResizable(false);
        choosePeople.setVisible(true);
    }//GEN-LAST:event_chooseButtonActionPerformed

    private void maNhanKhaujtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maNhanKhaujtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maNhanKhaujtfActionPerformed

    private void tenNhanKhaujtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenNhanKhaujtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenNhanKhaujtfActionPerformed

    private void soCCCDjtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soCCCDjtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soCCCDjtfActionPerformed

    private void jCheckBoxBinhThuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBinhThuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxBinhThuongActionPerformed

    private void jCheckBoxHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxHoActionPerformed

    private void jCheckBoxSotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSotActionPerformed

    private void jtfKhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfKhacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfKhacActionPerformed

    private void SavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebtnActionPerformed
        // TODO add your handling code here:
        SucKhoeService sucKhoeService = new SucKhoeService();
        if(this.maNhanKhaujtf.getText().trim().isEmpty()){
            JOptionPane.showConfirmDialog(null, "Vui lòng chọn người khai báo");
        } else {
            sucKhoeModel.setNhanKhauID(nhanKhauBean.getNhanKhauModel().getID());
            if(trieuChungCheckBox.getState()) {
                sucKhoeModel.setTrieuChungCovid(1);
            } else sucKhoeModel.setTrieuChungCovid(0);
            sucKhoeModel.setNgayCapNhat(ngayCapNhatJDC.getDate());
            StringJoiner stringJoiner = new StringJoiner(", ");
            if(jCheckBoxBinhThuong.isSelected()) stringJoiner.add(jCheckBoxBinhThuong.getText());
            if(jCheckBoxHo.isSelected()) stringJoiner.add(jCheckBoxHo.getText());
            if(jCheckBoxSot.isSelected()) stringJoiner.add(jCheckBoxSot.getText());
            if(!jtfKhac.getText().trim().isEmpty()) stringJoiner.add(jtfKhac.getText().trim());
            sucKhoeModel.setTrangThaiSucKhoe(stringJoiner.toString());
            if(sucKhoeService.insertSucKhoe(sucKhoeModel)){
                JOptionPane.showMessageDialog(null, "Thêm thành công");
                SucKhoeManagePanel sucKhoeManagePanel = (SucKhoeManagePanel)this.parentPanel;
                sucKhoeManagePanel.getController().reset();
                close();
            }
        }
    }//GEN-LAST:event_SavebtnActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
            close();
        }
    }//GEN-LAST:event_backBTNActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ThemMoiSucKhoeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ThemMoiSucKhoeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ThemMoiSucKhoeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ThemMoiSucKhoeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ThemMoiSucKhoeFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Savebtn;
    private javax.swing.JButton backBTN;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton chooseButton;
    private javax.swing.JCheckBox jCheckBoxBinhThuong;
    private javax.swing.JCheckBox jCheckBoxHo;
    private javax.swing.JCheckBox jCheckBoxSot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfKhac;
    private javax.swing.JLabel maNhanKhauLabel;
    private javax.swing.JTextField maNhanKhaujtf;
    private com.toedter.calendar.JDateChooser ngayCapNhatJDC;
    private javax.swing.JLabel ngayCapNhatLabel;
    private javax.swing.JLabel soCCCDLabel;
    private javax.swing.JTextField soCCCDjtf;
    private javax.swing.JLabel sucKhoeLabel;
    private javax.swing.JLabel tenNhanKhauLabel;
    private javax.swing.JTextField tenNhanKhaujtf;
    private java.awt.Checkbox trieuChungCheckBox;
    private javax.swing.JLabel trieuChungLabel;
    // End of variables declaration//GEN-END:variables
}
